//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinClean.resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinClean.resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ActivationKey ähnelt.
        /// </summary>
        public static string ActivationKey {
            get {
                return ResourceManager.GetString("ActivationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ActivationKeyInstallError.AccessDenied ähnelt.
        /// </summary>
        public static string ActivationKeyInstallError_AccessDenied {
            get {
                return ResourceManager.GetString("ActivationKeyInstallError.AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ActivationKeyInstallError.ComputerActivationFailed ähnelt.
        /// </summary>
        public static string ActivationKeyInstallError_ComputerActivationFailed {
            get {
                return ResourceManager.GetString("ActivationKeyInstallError.ComputerActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ActivationKeyInstallError.NotActivatingWindows ähnelt.
        /// </summary>
        public static string ActivationKeyInstallError_NotActivatingWindows {
            get {
                return ResourceManager.GetString("ActivationKeyInstallError.NotActivatingWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ActivationKeyInstallError.NotGenuineWindows ähnelt.
        /// </summary>
        public static string ActivationKeyInstallError_NotGenuineWindows {
            get {
                return ResourceManager.GetString("ActivationKeyInstallError.NotGenuineWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ActivationKeyInstallError.Other ähnelt.
        /// </summary>
        public static string ActivationKeyInstallError_Other {
            get {
                return ResourceManager.GetString("ActivationKeyInstallError.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ActivationKeyInstallError.ProductKeyBlocked ähnelt.
        /// </summary>
        public static string ActivationKeyInstallError_ProductKeyBlocked {
            get {
                return ResourceManager.GetString("ActivationKeyInstallError.ProductKeyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ActivationKeyInstallError.ProductKeyInvalid ähnelt.
        /// </summary>
        public static string ActivationKeyInstallError_ProductKeyInvalid {
            get {
                return ResourceManager.GetString("ActivationKeyInstallError.ProductKeyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.ActivationKeyInstallError.ProductKeyNotWorking ähnelt.
        /// </summary>
        public static string ActivationKeyInstallError_ProductKeyNotWorking {
            get {
                return ResourceManager.GetString("ActivationKeyInstallError.ProductKeyNotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.EnterActivationKey ähnelt.
        /// </summary>
        public static string EnterActivationKey {
            get {
                return ResourceManager.GetString("EnterActivationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.EnterActivationKeyError ähnelt.
        /// </summary>
        public static string EnterActivationKeyError {
            get {
                return ResourceManager.GetString("EnterActivationKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.EnterToContinue ähnelt.
        /// </summary>
        public static string EnterToContinue {
            get {
                return ResourceManager.GetString("EnterToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.EnterToExit ähnelt.
        /// </summary>
        public static string EnterToExit {
            get {
                return ResourceManager.GetString("EnterToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.FatalErrorDefault ähnelt.
        /// </summary>
        public static string FatalErrorDefault {
            get {
                return ResourceManager.GetString("FatalErrorDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.HasActivationKeySelection ähnelt.
        /// </summary>
        public static string HasActivationKeySelection {
            get {
                return ResourceManager.GetString("HasActivationKeySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.HasActivationKeySelectionAnswerN ähnelt.
        /// </summary>
        public static string HasActivationKeySelectionAnswerN {
            get {
                return ResourceManager.GetString("HasActivationKeySelectionAnswerN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.HasActivationKeySelectionAnswerY ähnelt.
        /// </summary>
        public static string HasActivationKeySelectionAnswerY {
            get {
                return ResourceManager.GetString("HasActivationKeySelectionAnswerY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.HasActivationKeySelectionError ähnelt.
        /// </summary>
        public static string HasActivationKeySelectionError {
            get {
                return ResourceManager.GetString("HasActivationKeySelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.LanguageSelectionError ähnelt.
        /// </summary>
        public static string LangaugeSelectionError {
            get {
                return ResourceManager.GetString("LangaugeSelectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die string.LanguageAlreadySet ähnelt.
        /// </summary>
        public static string LanguageAlreadySet {
            get {
                return ResourceManager.GetString("LanguageAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.OsNotWindows ähnelt.
        /// </summary>
        public static string OsNotWindows {
            get {
                return ResourceManager.GetString("OsNotWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.OsNotWindows10 ähnelt.
        /// </summary>
        public static string OsNotWindows10 {
            get {
                return ResourceManager.GetString("OsNotWindows10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.Part1TitleBar ähnelt.
        /// </summary>
        public static string Part1TitleBar {
            get {
                return ResourceManager.GetString("Part1TitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.SelectionNotInRange ähnelt.
        /// </summary>
        public static string SelectionNotInRange {
            get {
                return ResourceManager.GetString("SelectionNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.SelectionNotNumber ähnelt.
        /// </summary>
        public static string SelectionNotNumber {
            get {
                return ResourceManager.GetString("SelectionNotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.SelectionSelect ähnelt.
        /// </summary>
        public static string SelectionSelect {
            get {
                return ResourceManager.GetString("SelectionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.TitleWelcome ähnelt.
        /// </summary>
        public static string TitleWelcome {
            get {
                return ResourceManager.GetString("TitleWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.WelcomeMessage ähnelt.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.WindowsAlreadyActivated ähnelt.
        /// </summary>
        public static string WindowsAlreadyActivated {
            get {
                return ResourceManager.GetString("WindowsAlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strings.WindowsNotAlreadyActivated ähnelt.
        /// </summary>
        public static string WindowsNotYetActivated {
            get {
                return ResourceManager.GetString("WindowsNotYetActivated", resourceCulture);
            }
        }
    }
}
